diff --git a/drivers/Makefile b/drivers/Makefile
index 6fba7daba..eeff3dc1a 100644
--- a/drivers/Makefile
+++ b/drivers/Makefile
@@ -9,6 +9,8 @@
 obj-y				+= irqchip/
 obj-y				+= bus/
 
+obj-y += ps2_counter.o
+
 obj-$(CONFIG_GENERIC_PHY)	+= phy/
 
 # GPIO must come after pinctrl as gpios may need to mux pins etc
